### ISSUE TITLE
Custom colors, icons and damage merging

### ISSUE THREAD

**Issue by Exeges** [dandruff/xCT#58]
1. Using a custom color for incoming spell damage colors the attacks of physical special attacks. No way to separate actual spell damage and physical damage?
2. No icon support for incoming damage and healing?
3. Multiple sources of incoming damage get merged into a single event. Any way to split events up or at least add a notification, i.e "-2843 (2 hits)"?

**Comment by Cimplex** [comment]
1. To the best of my knowledge this should be working. Please let me know if you are on 4.0.3 beta (from Curse) and have adjusted these options: ![SS](https://db.tt/VllAGvAf)

2. None. This would require an overhaul of what I am doing to get Combat Events (I am not hooking the combat event log for incoming events, only outgoing. This has the advantage of being faster since Blizzard's combat is always running in the background, why not hook into that instead). I would love to implement it, but I have not gotten to it yet.

3. I guess I am confused. Incoming damage should not be merged, is this something you want? Or can you give me a specific example of where they are getting merged? I could probably put in a check to split it.

I really hope this helps. Please let me know about issue one and three, I will keep checking back. I am sorry about issue two, but I just don't have a lot of free time as of now. Thanks for helping me xCT+ better though! I really appreciate any feedback or criticism.

**Comment by Exeges** [comment]
1. I'm on the latest version from curseforge. Issue persists (see image). I'm guessing blizzard classifies it as a spell, but the actual damage is not spell damage but physical. This is what I'd like to have different colors for - physical and spell damage.
![wowscrnshot_021115_111125](https://cloud.githubusercontent.com/assets/10924891/6145184/572cead8-b1df-11e4-8881-f99015c3ae55.jpg)

2. Too bad :( kind of deters me from dropping MSBT in favor of your lovely addon. Icons really help determine sources of damage as a tank.

3. I was actually mistaken! Ignore this one.

**Comment by RedAces** [comment]
Should be fixed!
